main: com.thizthizzydizzy.resourcespawner.ResourceSpawnerCore
version: 1.2.0-beta.10
api-version: 1.16
name: ResourceSpawner
commands:
    resourcespawner:
        description: ResourceSpawner commands
        usage: /resourcespawner help|debug [on|off]|scan
softdepend: [WorldEdit, WorldGuard]